### ISSUE TITLE
Consider combining M3/M4

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#130]
We currently have separate objectives for "M3 Finding matrix inverse" and "M4 Determine if matrix is invertible". I'm organizing activities by outcome for the PreTeXt conversion and it's hard to sever these.

These could be combined, with assessment exercises such as:

> Let A=[..] and B=[..]
>
> - Explain which of these matrices is invertible, and which one is not.
> - Explain how to calculate the inverse of the invertible matrix.

**Comment by siwelwerd** [comment]
This may be more of an indication that organization of the materials into discrete learning outcomes is not ideal.

**Comment by StevenClontz** [comment]
Hard disagree. As the project expands over the next three years, we need to provide instructors an elegant mechanism to pick and choose which outcomes satisfy their institution's requirements for their course. Having a bijection between sections and outcomes is the most elegant solution I can think of.

**Comment by siwelwerd** [comment]
Maybe we need to think harder then 🙃. It's well established that interleaving improves student learning. And outside of this particular context, sometimes there are motivating activities that are not done in order. Since I've been doing it last week, off the top of my head Module E starts with some motivating activities about E3, then does some E1 and E2, then back to E3.

Logically, I am wondering if it makes more sense to have each activity/thing/whatever tagged with outcome(s).  Then the activities could be filtered against an instructor-provided subset of outcomes.  And ideally, there would be some automation of dependency among the outcomes.

Or maybe we need to have some mechanism of having "core topics" that are always present, and "optional topics" that can be added or dropped as needed. Then the "core topics" could be messier and more intermingled, as determined by what promotes student learning best, and the "optional topics" would be required to be self-contained by outcome. Going back to the module E example, E1 and E3 would be "core" topics, with E2 a self-contained "optional topic"

**Comment by StevenClontz** [comment]
Having one section per outcome isn't mutually exclusive with interleaving. Let's say an instructor only wants E1&E3. Then their materials could omit section E2, as well as any activities in other sections that are only tagged with E2. I like having a notion of core outcomes for each module, with non-core outcomes explicitly defining their dependencies. Modules can also have dependencies on (core outcomes from) other modules.

Aside from this argument, I don't understand why M3/M4 are assessed separately anyway. I bet if we look at the data, understanding how to compute a matrix inverse almost always implies understanding of matrix invertibility.

**Comment by siwelwerd** [comment]
My point was that E1 and E3 are pretty inseparable, and there is E3 stuff mixed into E1. So if an instructor wants E1 but not E3, the activities as is don't make a lot of sense; but why would anyone want that? I guess I am thinking of a dependency graph that is not a tree. 

As to the original narrow question, at some point a choice has to be made, and that's the one that was made. Then, following backwards design principles, activities were created to align to those standards. I don't feel super strongly either way that separate or together is better or worse from an assessment standpoint.

**Comment by siwelwerd** [comment]
Having done this again more recently, I am more inclined to keep them separate so that students have a couple easier standards later in the semester.

**Comment by StevenClontz** [comment]
I do like that game design effect. I'm closing this. I think at this point questions like "should M3/M4 be separate PreTeXt `<section>`s?" should be deferred to discussions with the community that our IUSE grant will support around these materials, since they will have their own perspectives on how they can best use these materials.
