### ISSUE TITLE
PTX: Build Tikz diagrams

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#133]

**Comment by siwelwerd** [comment]
Started working on this in https://github.com/TeamBasedInquiryLearning/linear-algebra/tree/tikz .  See https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/5ef44ab50a32f85f1df457d07ab960393b60bfe3/ptx/source/02-V/03.ptx#L11 for an example of how to do this.

At the moment, there is an issue caused by using the enclose package (which we we use in the \circledNumber macro to circle pivots).  I think the culprit is that the \require{enclose} should not be in <macros> (which gets used in the latex image production), but I don't know where it belongs instead. The \require{enclose} is a MathJax thing, and not part of LaTeX, so that is what seems to be breaking it.

**Comment by StevenClontz** [comment]
pretext-support discussion at https://groups.google.com/g/pretext-support/c/ZfwJtpferUw/m/AJzkCBPXAgAJ

**Comment by StevenClontz** [comment]
@siwelwerd To avoid merge conflicts I'm assigning you to audit the content between E1 and G4 to address

- #129 
- #133 (this)
- #143 
- #149
- #150

Right now, I believe E1 and V3 are set up correctly. Note that I'm sorting each section into two subsections, `Activities` and `Videos`, followed by `Exercises`.

Meanwhile I'll work on adding new sections for e.g. Sample Exercises.

**Comment by StevenClontz** [comment]
(You can continue working on the `tikz` branch updated to a8f8aed1 )

**Comment by StevenClontz** [comment]
Oh, note also the addition of `<caption/>`s -- we didn't have those in LaTeX, but for accessibility (and to look "right") we need to add them now.

**Comment by siwelwerd** [comment]
> To avoid merge conflicts I'm assigning you to audit the content between E1 and G4

Could you clarify what you mean by "audit the content"?

**Comment by StevenClontz** [comment]
Read through it and make sure we've addressed the issues I mention above (e.g. images have captions, your videos have been added, etc.).

**Comment by siwelwerd** [comment]
This is almost done, the image in Figure 4.1.1 is apparently a commutative diagram. The PreTeXt way of creating commutative diagrams does not seem to allow for curved arrows though, need to find a workaround.
