### ISSUE TITLE
Interactive geometry elements

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#165]
Some activities like 2.2.1-2.2.3 would benefit from interactive geometric elements--I threw some things into Desmos on the spur of the moment in class today, and it was effective, but would be more effective if they were playing with them instead of me. Desmos is just an example, I am not sure at the moment what other options would be a) easier to implement, or b) possibly more effective.

**Comment by StevenClontz** [comment]
I'm somewhat inclined to implement Octave visualizations over Desmos. Desmos is much easier to play with certainly, but it's not FOSS, and fostering comfort with Octave/Matlab is of more value long-term.

Here's an animation I use in Diff EQ with SageMath: https://sagecell.sagemath.org/?z=eJyNjkEKgzAQRfeeYsgqqWOrgtCNJymthBpLMCYh2jK5fdWiFLrpXz0-nzdDGOuXDJwRRCYSafUgJ8XhAt64qRmN86rptDItLw_xRAicMCtyLHIxc9xYpN5pO3Fe4lng3RkXauafwRvFRJrAnkU7q-hW4iZCGrStFwYaJNULxL2Kn-pXAv1qgfmndZhvZ4Nq2V9OEF_ONZ0L0IO2MFKQ9qF4VmGFx1LAFcQbCQxQSQ==&lang=sage&interacts=eJyLjgUAARUAuQ==

**Comment by siwelwerd** [comment]
Yeah, what I like about Desmos is that the interface makes interactivity super easy (add some sliders and you're off). I'll have to look in to how to use Octave to make interactive things.

**Comment by StevenClontz** [comment]
It was probably too much to hope for, but ipywidgets (what I use to make a UI for CheckIt in Jupyter) does not play with SageMathCell, and I'd expect Octave would be less likely to have widget support. https://sagecell.sagemath.org/?z=eJzLzC3ILypRyCyoLM9MSU8tKVZILFaAMrm4inNK04sVbBWi1RPVdRTUk5JBZEpqGohKV4_lSinKLwBKQ9XruQC5KfnleRr5BSWZ-XnFtmD9mlwpmcUFOYmVGiDlmgCm5ibb&lang=sage&interacts=eJyLjgUAARUAuQ==

If a sidegoal of our book is to get kids using Octave, maybe it's worth the extra cognitive overload in having them modify Octave code to create visualizations, rather than using slick Desmos applets.

**Comment by siwelwerd** [comment]
I'm not that tied to Octave, and I am skeptical that what little exposure they are getting in our class is transferring in a useful way to their engineering classes. So I'm skeptical that it would be worth the cognitive overload.

**Comment by StevenClontz** [comment]
I don't believe we're doing anything to create fluency, but I'm betting we're contributing a small part to foster familiarity/comfort. I wonder if "coding anxiety" is a similar concept to "math anxiety".

**Comment by siwelwerd** [comment]
I think this is too vague, specific places for interactives should be highlighted in individual issues such as https://github.com/TeamBasedInquiryLearning/library/issues/19 .  Closing this as a wontfix.
