### ISSUE TITLE
Consider adding E standard on number of solutions

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#175]
This would address two issues:

- It is the last week of class, and I am still seeing students unable to look at a RREF matrix and correctly identify if it has a solution or not (as many subsequent standards reduce to this kind of question).
- This would allow us to make the current E3 more uniform by only asking for the solution set of a system with infinitely many equations.

**Comment by StevenClontz** [comment]
I like this. Since my pivot to async quizzing I've become more comfortable with longer questions, e.g. https://checkit.clontz.org/#/banks/clontz-diff-eq/CC3 - I had 3 things I wanted to check (imaginary roots, repeated roots, and higher-order ODEs) so I just rigged 3 examples that covered each type. So another option is to have E3 have 3 systems covering the 3 cases, and for each system the student identifies how many solutions and describes the solution set.

**Comment by siwelwerd** [comment]
Yeah, the benefit to separating them is that we can emphasize that you don't have to completely solve it to know how many solutions there are, which is useful on certain things.  

Agreed on giving them one of each type for one of these, but if we also make these changes (https://github.com/TeamBasedInquiryLearning/checkit-tbil-la/issues/16) to E3, might be more manageable to separate into two standards.  But then it might be harder to separate the textbook sections... :)
