### ISSUE TITLE
Consider definition of basis to be an ordered tuple, not an unordered set

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#180]
Via Steve Gubkin

> I would prefer if a basis is an ordered list of vectors, rather than a set.

I thought about it for (only) a few minutes, and it definitely would have some advantages, particularly when considering repeated vectors in a basis. Technically for us, `{a,b,c,b}` might be a basis that *appears* to have 4 elements, even though b is repeated. It has the downside (maybe?) that `<a,b,c>` and `<c,b,a>` are different bases.

Maybe a question to bounce off TBIL fellows?

**Comment by siwelwerd** [comment]
I have 8 introductory books in my office, and 7 of them say "set" (the 8th is ambiguous about what it means). Axler's (notoriously contrarian) book uses lists of vectors. The more general algebra texts (like Lang) say set. So I am disinclined to differ from the consensus.

What most of these books do though, is also consider *ordered bases*, which we don't (yet). That is something that makes sense to me to include (we didn't because we didn't get into change of basis matrices).

**Comment by StevenGubkin** [comment]
You need an ordered basis to write down a matrix for any linear map, even if you are not doing change of basis.  For instance, what is the matrix of the derivative on the space of polynomials of degree less than or equal to 5 in the basis of monomials?  One needs to decide on an ordering!  The ordering most mathematicians would choose (ascending degree) is different from the one most students would choose (they have been trained to write polynomials in descending degree order).

**Comment by siwelwerd** [comment]
Sure, at the moment these activities only work with matrices for maps between Euclidean spaces, with the implicit understanding that these are using the typical ordering of the standard basis.  One of our focuses this summer is to expand the activities to be more applicable to broader contexts, rather than our local context we had in mind when authoring them.

**Comment by StevenClontz** [comment]
Here's the context from our activity sequence: Definition 3.2.3 
https://teambasedinquirylearning.github.io/linear-algebra/A2.html#definition-19
