### ISSUE TITLE
MX4 additional task

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#325]
I'd like to add an additional task to MX4 to assess all three types of row operations, and to add more variety in how these matrices are applied to the matrix.

I'm also somewhat interested in mixing in column operations and right-mulitiplication as well.

**Comment by siwelwerd** [comment]
First part seems fine.

As far as column operations/right multiplication, I'm more hesitant because they aren't really well motivated at this point.  I guess they could be motivated in EV6 via activities as ways to simplify the collection of vectors in a spanning set, eventually to produce a basis?  That seems like a bigger change worthy of a separate isssue.
