### ISSUE TITLE
Slideshow and exercise links are out-of-date

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#339]
I believe most (all?) of the slideshow and exercise links point to the 2023 versions in the current public version of the text

**Comment by siwelwerd** [comment]
Note that the section-by-section slideshows are deprecated, so those should just be removed (see also #335).

For the exercise links, maybe @StevenClontz knows if there is a way to change these to relative links rather than hardcoded URLs so we don't have to remember to change this with every version.

**Comment by StevenClontz** [comment]
I know there's a way to link assets (e.g. files in the `assets` directory); it's unclear if there's a slick way to link to content not managed by PreTeXt. (Importantly, a PDF has no idea where it "lives" without hardcoding a URL.)

**Comment by siwelwerd** [comment]
Maybe the approach then is a script that can get run to do the versioning changes to keep things from being overlooked.  I think this particular thing is a `sed` one-liner, but what other manual steps did you have to do to push a new version?

**Comment by StevenClontz** [comment]
To archive a finalized edition and create a new preview edition:

Update deploy-dirs at https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/main/project.ptx

Update subtitles at https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/main/source/main.ptx

Update title at https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/main/exercises/bank.xml

Archive finalized edition at https://github.com/TeamBasedInquiryLearning/linear-algebra/tree/main/site

Probably other stuff I'm forgetting because I haven't automated this yet, in the hopes that CLI adds built-in version support. (Though it probably wouldn't also support all the extra CheckIt stuff anyway I guess.)

**Comment by siwelwerd** [comment]
Tried to take our tangent discussion over to #345 so it will persist after we fix this acute issue.
